version: 2
updates:
  - package-ecosystem: terraform
    directory: "/testing"
    schedule:
      interval: weekly
      time: "02:00"
    open-pull-requests-limit: 20
    allow:
      - dependency-type: direct
      - dependency-type: indirect
